name: animalia_academy
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  uuid: ^3.0.4
  email_validator: ^3.0.0
  provider: ^5.0.0

  audioplayers: ^6.0.0
  sizer: ^2.0.15
  flutter_animate: ^4.5.0
  flutter_spinkit: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/audio/
    - assets/audio/music/
    - assets/audio/sfx/
    - assets/audio/sfx/animal_sounds/
    - assets/audio/sfx/app_sounds/
    - assets/images/
    - assets/images/animal_categories/
    - assets/images/animals/
    - assets/images/backgrounds/
    - assets/images/animal_habitats/
    - assets/images/logos/

  fonts:
    - family: Anek-Latin
      fonts:
        - asset: assets/fonts/Anek-Latin/AnekLatin-Regular.ttf
